### PR TITLE
Khalid's Playlist Page

### PR DESCRIPTION
**Pull request by khalludi**
A playlist page with a miniplayer. Mostly just the UI portion. Functionality will be added separately.

Picture:
image

### CODE REVIEW

**Review by Himnish — COMMENTED** [review]
Looks good, a lot of stuff seems constant though, is there scope to make text and info dynamic? Also how are we getting playlist information displayed on this page

**Comment by khalludi** [comment]
The whole idea is more to just get the design elements correct. The actual functionality would be added separately since that will take a considerable amount of effort. I didn't want to overload the PR.

Yea, the dynamic functionality will take some more effort. I think the playlist creation logic will be happening behind-the-scenes, so we can have some sort of loading functionality where we inform the user that we are making the playlist. Once we have the playlist, we can query whatever track information we need. Then, when we transition from "Loading" state to "Playable" state, we can use the info we got from Spotify to populate the necessary fields. 

The Playlist Creation widget has a bunch of helpers on how to call the Spotify API. We can use that framework in this Player page to perform playback and animate the progress bar as necessary. I'm thinking that we create a separate widget for this page to hold most of the backend Spotify calls, and we can pass the info to this widget for display. 

Let me know if you have any more questions or need some help figuring out how to integrate the Spotify stuff.

**Comment by Himnish** [comment]
Alright cool

**Comment by khalludi** [comment]
Continued in #20

**Pull request closed without merging**
